# <center>Laboratorium 1<br>Metody Numeryczne</center>

Biblioteki niezbędne do wykonania zadania:

(wykonanie tego bloku zapewnia do nich dostęp w kolejnych blokach)

In [2]:

#!/usr/bin/python
# -*- coding: utf-8 -*-
import main
import math

import numpy as np
import scipy

Przydatne w trakcie zajęć mogą okazać się metody macierzy z pakietu Numpy, takie jak na przykład długość wektora - *[len]()* czy rozmiar macierzy -
*[shape](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.shape.html#numpy.ndarray.shape)*. Poniższy kod ilustruje ich podstawowe działanie. Dodatkowe metody obiektu $ndarray$ można znaleźć w oficjalnej *[dokumentacji](https://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html)*.

In [5]:
vector = np.array([1, 2, 3])
print('Wektor:')
print(vector)
print('Długość:', len(vector))
print('Rozmiar:', vector.shape, '\n')

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('Macierz:')
print(matrix)
print('Rozmiar:', matrix.shape)

Wektor:
[1 2 3]
Długość: 3
Rozmiar: (3,) 

Macierz:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Rozmiar: (3, 3)


***Zadanie 1.***  
Zaimplementuj funkcję $cylinder\_area$ tak by zwracała pole powierzchni walca o promieniu podstawy $r$ i wysokości $h$. Stała $\pi$ jest zdefiniowana np. w bibliotece *[math](https://docs.python.org/3/library/math.html#constants)*. Jeżeli nie da się policzyć pola funkcja powinna zwracać wartość *NaN*. Sprawdź działanie zaimplementowanej funkcji dla dowolnych wartości w tym notatniku.

In [6]:
print(main.cylinder_area(2,1))

print(main.cylinder_area(-1,2))



37.69911184307752
nan


***Zadanie 2.***  
Wygeneruj dowolne ciągi arytmetyczny o kroku różnym od jeden i niebędącym liczbą całkowitą, używając w tym celu funkcji *[arange](https://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html)* oraz *[linspace](https://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.linspace.html)*. Wypisz go i przeanalizuj otrzymane rezultaty.


In [7]:
print("Arrange method")
print("", np.arange(1.1,8.1,1))
print("Linspace method")
print("", np.linspace(2.2,6.2,num=5))


Arrange method
 [1.1 2.1 3.1 4.1 5.1 6.1 7.1]
Linspace method
 [2.2 3.2 4.2 5.2 6.2]


Komentarz:Zapoznanie się z dwiema funkcjami arange() oraz linspace() do genereowania ciągu arytmetycznego  

***Zadanie 3.***  
Zaimplementuj funkcję $fib$ zwracającą wektor pierszych n elementów *[ciągu Fibonnaciego](https://pl.wikipedia.org/wiki/Ci%C4%85g_Fibonacciego)*, jeżeli nie jest to możliwe funkcja powinna zwrócić wartość *None*.

In [6]:
print(main.fib(5)) #5 pierwszych wyrazów
print(main.fib("a"))
print(main.fib(-1))
print(main.fib(2.0))


[[1 1 2 3 5]]
None
None
None


Działanie funkji wydaje się być poprawne. Dla liczb całkowitych zwaracanych jest wektor, natomiast dla stringa oraz floata zwracana jest wartość None. 

***Zadanie 4.***  
Napisz funkję $matrix\_calculations$ która jako argument przyjmuje dowolną wartość liczbową *a* i tworzy macierz:  
  
$\mathbf{M} =\left[ \begin{matrix}
a & 1 & -a\\
0 & 1 & 1\\
-a & a & 1
\end{matrix}\right]
$    
   
Dla zadeklarowanej macierzy wyznacz numerycznie macierz odwrotną $\mathbf{Minv}$ (jeżeli nie istnieje taka macierz wartość wynosi NaN), macierz transponowaną $\mathbf{Mt}$ i wyznacznik macierzy $\mathbf{Mdet}$. Zwróć otrzymane wartości w postaci krotki postaci $(\mathbf{Minv}, \mathbf{Mt}, \mathbf{Mdet})$.  Wypisz otrzymane wyniki. 
  
***Wskazówki:*** Do tworzenia obiektów mających własności macierzy w języku Python używa się klasy *[array](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.array.html)* z pakietu *[numpy](http://www.numpy.org/)*, przykładowe użycie:

In [8]:
import numpy as np # słowo kluczowe "as" oznacza przesłania nazwę numpy i pozwala  
a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])
A = np.array([[1,2],[3,4]])
print("Wektor poziomy:\n {0}".format(a))
print("Wektor pionowy:\n {0}".format(b))
print("Macierz:\n {0}".format(A))



Wektor poziomy:
 [1 2 3]
Wektor pionowy:
 [[1]
 [2]
 [3]]
Macierz:
 [[1 2]
 [3 4]]


In [9]:
print(main.matrix_calculations(5))

(array([[ 0.08,  0.52, -0.12],
       [ 0.1 ,  0.4 ,  0.1 ],
       [-0.1 ,  0.6 , -0.1 ]]), array([[ 5,  0, -5],
       [ 1,  1,  5],
       [-5,  1,  1]]), -49.99999999999997)


Komentarz:
Zapoznanie się z funkcjami, za pomocą których możemy wykonywać operacje na macierzach m.in wyznaczanie macierzy odwrotnej, wyznacznika, transpozycji oraz zwracania wartości za pomocą krotki.

Do wykonania operacji odwracania macierzy należy użyć funkcji *[inv](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.inv.html)*, do obliczenia wyznacznika macierzy stosuje się funkcję *[det](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.linalg.det.html)*  z bliblioteki *[linalg](https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)*. Natomiast transpozycję macierzy wykonujemy przez funkcję *[transpose](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.transpose.html)* której skrucona wersja to $M.T$ z pakietu *numpy*.  
    
*Ciekawostka:* Python natywnie nie zawiera struktury danych typu tablica, na poziomie języka jest to rozwiązane poprzez strukturę listy list do której elementów odwołuje się poprzez indeksy jak w C/C++.

In [ ]:
Komentarz:
Zapoznanie się z biblioteką linalg, dzięki której możemy używać funkcji inv, det oraz transpose.

***Zadanie 5.***  
Stwórz w noataniku macierz:  
$\mathbf{M} =\left[ \begin{matrix}
3 & 1 & -2 & 4\\
0 & 1 & 1 & 5\\
-2 & 1 & 1 & 6\\
4 & 3 & 0 & 1\\
\end{matrix}\right]
$   
Wypisz przy pomocy funkcji *print* następujące elementy macierzy $\mathbf{M}$: $\mathbf{M}_{1,1},\mathbf{M}_{3,3},\mathbf{M}_{3,2}$. Zdefiniuj wektor $\mathbf{w1}$ którego elementy to trzecia kolumna macierzy $\mathbf{M}$ oraz wektor $\mathbf{w2}$ który składa się z drugiego wiersza tej macierzy.  
  
***Wskazówki:***
Tablice z pakietu *numpy* są indeksowane od zera a do każdego elementu można odwołać się poprzez jego indeks. Przykład użycie


In [4]:
M=np.array([[3,1,-2,4],[0,1,1,5],[-2,1,1,6],[4,3,0,1]])
print(M)
print(M[1,1])
print(M[3,3])
print(M[3,2])
w1=M[:,2]
w2=M[1,:]



# Inicjalizacja macierzy do przykładu
P = np.array([[1,3,2],[3,4, 6],[7,8,9]])
print("Macierz P=\n{0}".format(P))
# wyciągnięcie trzeciej kolumny 
wektor1 = P[:,2]
# wyciągnięcie trzeciego wiersza 
wektor2 = P[2,:]
print("Elementy trzeciej kolumny:\n {0}".format(wektor1))
print("Elementy trzeciego wiersza:\n {0}".format(wektor2))

[[ 3  1 -2  4]
 [ 0  1  1  5]
 [-2  1  1  6]
 [ 4  3  0  1]]
1
1
0
Macierz P=
[[1 3 2]
 [3 4 6]
 [7 8 9]]
Elementy trzeciej kolumny:
 [2 6 9]
Elementy trzeciego wiersza:
 [7 8 9]


Komentarz:
Ćwiczenie to w przejrzysty sposób pomogło mi inicjalizować macierz oraz wypisywać poszczególne jej elementy

Dodatkowo twórcy biblioteki umożliwiają użytkownikowi na manipulację elementami tablicy poprzez operator ':', więcej szczegółów na temat jego użycia w artykule [NumPy for Matlab users](https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html#numpy-for-matlab-users).

***Zadanie 6.***   
Uzupełnij funkcję $custom\_matrix$, tak by parametry m, n określały wymiary macierzy wynikowej, która
będzie wypełniona w/g algorytmu: jeśli indeks wiersza jest większy od indeksu kolumny
wartością komórki jest indeks wiersza, w przeciwnym wypadku wartością komórki jest indeks
kolumny. Funkcja jako wynik powinna zwracać uzupełnioną macierz, jeżeli nie jest to możliwe to powinna zwrócić *None*. Na koniec wyświetlić wynikową macierz dla dowolnych argumentów $m$, $n$ z przedziału $\langle3,7\rangle$.
  
***Wskazówka:*** Inicjalizacja pustej macierz wykonywana jest w pakiecie Numpy przy pomocy funkcji  *[zeros](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.zeros.html)*, zaś macierzy składającej się z jedynek *[ones](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)*.

In [11]:
zero_matrix = np.zeros((2, 2))
ones_matrix = np.ones((3,1))

print('zero_matrix: \n{}'.format(zero_matrix))
print('ones_matrix: \n{}'.format(ones_matrix))


zero_matrix: 
[[0. 0.]
 [0. 0.]]
ones_matrix: 
[[1.]
 [1.]
 [1.]]


In [12]:
print(main.custom_matrix(4,5))

[[0 1 2 3 4]
 [1 1 2 3 4]
 [2 2 2 3 4]
 [3 3 3 3 4]]


Komentarz:
Dzięki temu zadaniu nauczyłem się generować macierz pustą macierz oraz macierz jednostkową. Przypomniałem sobie działanie pętli for, która pozwoliła mi przechodzić między wierszami oraz kolumnami. Ćwiczenie to sprawiło mi trochę kłopotów ze względu na zagnieżdżanie pętli oraz warunku if.

***Zadanie 7.***

Biblioteka Numpy posiada własne metody, pozwalające na szybsze i wygotniejsze wykonywanie operacji na wektorach i macierzach. Kolejne zadania mają na celu przećwiczenie tych metod. Zamiast samemu implementować mnożenie macierzy, należy skorzystać właśnie z wbudowanych funkcji Numpy. Najbardzie podstawowe z nich to *[np.multiply](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.multiply.html)*, *[np.dot](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.dot.html)* oraz *[np.matmul](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.matmul.html)*. Przed wykonaniem zadania należy zapoznać się z ich dokumentacją, aby stosować poprawną funkcję do danego typu mnożenia. Dodatkowo ciekawą i użyteczną funkcjonalnością Numpy, wykorzystywaną niekiedy przy dodawaniu macierzy jest *broadcasting*, proszę o zapoznaie się z opisem:  *[[1]](https://docs.scipy.org/doc/numpy-1.15.0/user/basics.broadcasting.html)* *[[2]](https://www.tutorialspoint.com/numpy/numpy_broadcasting.htm)*.

Zainicjalizować dwa wektory $v_1$ i $v_2$:

$v_1 = \begin{bmatrix}1\\3\\13\end{bmatrix} \quad v_2 = \begin{bmatrix}8\\5\\-2\end{bmatrix}$

Następnie wykonać operacje i wypisać ich wynik:
- $4*v_1$
- $-v_2 + \begin{bmatrix}2\\2\\2\end{bmatrix}$
- $v_1 \circ v_2$ (w sensie mnożenia macierzy, tzw. mnożenie macierzy w sensie Cauchy’ego)
- $v_1 * v_2$ (w sensie mnożenia Hadamarda (element-wise))

***Wskazówki:*** Warto wiedzieć o *[np.dot](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.dot.html)* i *[np.multiply](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.multiply.html)*. Zbadać jak zachowuje się przeciążony operator mnożenia $*$ oraz $@$ dla macierzy $ndarray$.

In [5]:
v1 = np.array([[1],[3],[13]])
v2 = np.array([[8],[5],[-2]])
print(v1)
print(v2)
print("operacja_1")
operation_1= 4*v1
print(operation_1)
print("operacja_2")
operation_2= -v2 *np.array([[2],[2],[2]])
print(operation_2)
print("operacja_3")
operation_3 = np.matmul(np.transpose(v1), v2)
print(operation_3)
print("operacja_4")
operation_4 = np.multiply(v1,v2)
print(operation_4)
v3=np.array([[1],[3],[2]])
print("działanie przeciążenia operatora *")
print(v1*v3)
v4 =np.array([4,2,8])
print("działanie przeciążenia operatora @")
print(v4@v1)

print("Komentarz:Ogólna idea dotycząca przeciążenia polega na tym, że w prosty sposób można wykonać działania na macierzach.Metoda ta zwraca wynik jeżeli chodzi o mnożenie tablicowe oraz macierzowe.")

                          

[[ 1]
 [ 3]
 [13]]
[[ 8]
 [ 5]
 [-2]]
operacja_1
[[ 4]
 [12]
 [52]]
operacja_2
[[-16]
 [-10]
 [  4]]
operacja_3
[[-3]]
operacja_4
[[  8]
 [ 15]
 [-26]]
działanie przeciążenia operatora *
[[ 1]
 [ 9]
 [26]]
działanie przeciążenia operatora @
[114]
Komentarz:Ogólna idea dotycząca przeciążenia polega na tym, że w prosty sposób można wykonać działania na macierzach.Metoda ta zwraca wynik jeżeli chodzi o mnożenie tablicowe oraz macierzowe.


***Zadanie 8.***
Zainicjalizować macierz $M_1$:

$M_1 = \begin{bmatrix}1&-7&3\\-12&3&4\\5&13&-3\end{bmatrix}$

Następnie wykonać operacje i wypisać ich wynik:
- $3M_1$
- $3M_1 + \begin{bmatrix}1&1&1\\1&1&1\\1&1&1\end{bmatrix}$
- $M_1^T$
- $M_1 \circ v_1$ 
- $v_2^T \circ M_1$

In [3]:
M1=np.array([[1,-7,3],[-12,3,4],[5,13,-3]])
print(M1)
print("operacja_1")
print(M1*3)
print("operacja_2")
print(3*M1 + np.ones((3,3)))
print("operacja_3")
operation_3=np.transpose(M1)
print(operation_3)
print("operacja_4")
v1=np.array([[5],[2],[3]])
print(M1@v1)
print("operacja_5")
v2=np.array([[4],[2],[3]])
print(np.transpose(v2)@M1)
             


[[  1  -7   3]
 [-12   3   4]
 [  5  13  -3]]
operacja_1
[[  3 -21   9]
 [-36   9  12]
 [ 15  39  -9]]
operacja_2
[[  4. -20.  10.]
 [-35.  10.  13.]
 [ 16.  40.  -8.]]
operacja_3
[[  1 -12   5]
 [ -7   3  13]
 [  3   4  -3]]
operacja_4
[[  0]
 [-42]
 [ 42]]
operacja_5
[[-5 17 11]]


Komentarz:
W tym ćwiczeniu powtórzyłem sobie działanie operatora @ do wymnażania macierzy w sensie Cauchy'ego. Zbędna okazała się być funkcja multiply.

# Wnioski
-Powyższe ćwiczenia pozwoliły mi jednocześnie przypomnieć sobie podstawowe wiadomości dotyczące programowania w języka
python oraz poznać nową bibliotekę jaką jest numpy dołączana do interpretera anaconda 3.0. Nigdy nie sądziłem, że za
pomocą tej biblioteki można wykonywać inteligentne operacje na macierzach oraz wektorach.  
-Zapoznałem się notatnikiem jupyter notebook. Na samym początku nie był on dla mnie zbyt czytelny, lecz później 
uświadomiłem sobie, że będę go wykorzystywał w dalszym etapie programowania, ze względu na przejrzystość i czytelność
kodu programowania.  
-Polecania pomogły mi poznać dwie funkcje "isinstance()" oraz "atype()" dzięki którym mogę w prosty sposób sprawdzić,czy liczba jest całkowita lub innego typu. Według mnie lepszą funkcją okazuje się być "isinstance()" ponieważ sprawadza ona czy dany obiekt jest instancją podklasy. Funkcje "arange()" oraz "linspace()" w bardzo szybki sposób ułtawiają nam gernerowanie ciągu liczb różnego typu.  
-Głównym celem tego laboratorium były funkcje, które w łatwy i przyjemny sposób pozwalają dokonywać operacji na macierzach oraz wektorach np.inicjalizowanie macierzy,pomnożenie macierzy przez wektor, transpozycja macierzy,obliczanie wyznacznika macierzy,indeksowanie poszczególnych wartości w macierzy oraz ich wypisywanie.  
-Zadania te pozwoliły mi pokazać różnicę między wartością None, a wartością NaN. Ta druga wartość lepiej się nadaje do zwracania ponieważ jest typu float, która nie powoduje błędu i zawsze zwraca to samą wartość.   

Zajęcia te w bardzo szybki sposób stały się dla mnie bardzo przyjemne. Zafascynowało mnie to że za pomocą biblioteki numpy można wykonywać tak ciekawe operacje. Na początku okazały się one łatwe do definiowania. Mam zamiara poświęcić więcej czasu na ową bibliotekę jak i na samego pythona. Wsystkie ćwiczenia przeszły testy jednostkowe oraz zostały zrealizowane przeze mnie.

Wiktor Wiernasiewicz

Materiały uzupełniające:
- [Scipy Lecture Notes](http://www.scipy-lectures.org/index.html)
- [NumPy for Matlab users](https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html#numpy-for-matlab-users)
- [Python Tutorial - W3Schools](https://www.w3schools.com/python/default.asp)
- [NumPy](https://www.numpy.org)
- [Matplotlib](https://matplotlib.org/)
- [Anaconda](https://www.anaconda.com/)
- [Learn Python for Data Science](https://www.datacamp.com/learn-python-with-anaconda?utm_source=Anaconda_download&utm_campaign=datacamp_training&utm_medium=banner)
- [Learn Python](https://www.learnpython.org/)
- [Wujek Google](https://google.pl) i [Ciocia Wikipedia](https://pl.wikipedia.org/wiki/Wikipedia:Strona_g%C5%82%C3%B3wna)